server:
  port: 8080

# ===============================
# POSTGRES
# ===============================
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wander_book
    username: postgres
    password: 123456

# ===============================
# JPA / HIBERNATE
# ===============================
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    #        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# ===============================
# APP PROPERTIES
# ===============================
auth:
  token:
    jwtSecret: 88fcbfa02ebe24ac11ab6eb676f8cd89033920f202865bf874d73de7e5effde3
    expirationInMils: 3600000

#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
